name: CI
on:
pull_request:
push:
branches: [dev, main]
jobs:
ci:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- uses: actions/setup-python@v5
with: { python-version: "3.11" }
- name: Install
run: |
python -m pip install --upgrade pip
python -m pip install -e .[dev]
- name: Lint & Typecheck
run: |
ruff check .
black --check .
isort --check-only .
mypy apps ml
- name: Tests
run: pytest -q
- name: API import check
run: python - <<'PY'
import importlib
importlib.import_module("apps.api.main")
print("API import OK")
PY
